apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: vc-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io/v1
  kind: Role
  name: vc-role
subjects:
- kind: ServiceAccount
  name: valcon-sa
  namespace: default